language:
  - python

python: 3.6

# Currently Travis doesn't support multiple values for language variable
#  - cpp

#compiler:
#  - gcc

cache:
  ccache: true

env:
  global:
    # variables for caching
    - CCACHE_DIR=$HOME/.ccache
    - CCACHE_COMPILERCHECK=content
    - CCACHE_COMPRESS=true
    - CCACHE_NODISABLE=true
    - CCACHE_MAXSIZE=500M

matrix:
  include:
  - dist: xenial
    python: "2.7"
    env: GCC_VER=5.4 BUILD_BIGARTM_CLI=ON BUILD_PYTHON=OFF
  - dist: xenial
    python: "2.7"
    env: GCC_VER=5.4 BUILD_BIGARTM_CLI=OFF BUILD_PYTHON=ON
  - dist: xenial
    python: "3.5"
    env: GCC_VER=5.4 BUILD_BIGARTM_CLI=OFF BUILD_PYTHON=ON
  - dist: xenial
    python: "3.6"
    env: GCC_VER=5.4 BUILD_BIGARTM_CLI=OFF BUILD_PYTHON=ON
  - dist: xenial
    python: "3.7"
    env: GCC_VER=5.4 BUILD_BIGARTM_CLI=OFF BUILD_PYTHON=ON

before_install:
  - echo "before_install start"
  - travis_scripts/before_install.sh
  - echo "before_install done"

install:
  - echo "install start"
  - travis_scripts/install.sh
  - echo "install done"

before_script:
  - pushd test_data && ./download_datasets.sh && popd

script:
  - export ARTM_SHARED_LIBRARY=`pwd`/build/lib/libartm.so
  - export BIGARTM_UNITTEST_DATA=`pwd`/test_data
  - pushd build && make test ARGS="-V" && popd
