language:
  - python
# Currently Travis doesn't support multiple values for language variable
#  - cpp

#compiler:
#  - gcc

# not sure whether the following configuration will be available
# with non-C/C++ language (e.g python)
#cache: ccache

cache:
  pip: true
  directories:
    - $HOME/.ccache

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  global:
    # variables for caching
    - CCACHE_DIR=$HOME/.ccache
    - CCACHE_COMPILERCHECK=content
    - CCACHE_COMPRESS=true
    - CCACHE_NODISABLE=true
    - CCACHE_MAXSIZE=500M
  matrix:
    - GCC_VER=5.4

before_install:
  - echo "before_install start"
  - travis_scripts/before_install.sh
  - echo "before_install done"

install:
  - echo "install start"
  - travis_scripts/install.sh
  - echo "install done"

before_script:
  - pushd test_data && ./download_datasets.sh && popd

script:
  - export ARTM_SHARED_LIBRARY=`pwd`/build/lib/libartm.so
  - export BIGARTM_UNITTEST_DATA=`pwd`/test_data
  - pushd build && make test ARGS="-V" && popd
